on:
  workflow_run:
    workflows: [Integration Tests]
    types: [completed]

jobs:
  integration-tests-failure:
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.conclusion == 'failure' &&
        github.event.workflow_run.event == 'pull_request_target'
      }}
    steps:
      - run: |
          echo '${{ toJson(github.event.workflow_run) }}'
